kind: Deployment
apiVersion: apps/v1
metadata:
  name: test-repo
  namespace: test-repo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-repo
  template:
    metadata:
      labels:
        app: test-repo
    spec:
      containers:
        - name: test-repo
          image: quay-registry-quay-openshift-operators.apps.rnd.ocp.local/test-repo/test-repo:v1.0
          ports:
            - containerPort: 8080
              protocol: TCP
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
